### PR TITLE
add https support

### PR DESCRIPTION
**Pull request by jensendw**
This change adds https support.

### CODE REVIEW

**Comment by jensendw** [comment]
Any input on this?  I'm hoping to get it included so we can stop running off our own fork.

**Comment by malpani** [comment]
@jensendw thanks for the change - yes it looks good. Just wanted to do some testing. Plan is to merge this in on 11/19

**Comment by jensendw** [comment]
@malpani thanks!

**Comment by malpani** [comment]
@jensendw thank you for the fix. Have pulled it in

**Pull request merged**
