### PR TITLE
Update logstash-output-amazon_es.gemspec

### PR DESCRIPTION
**Pull request by Alien2150**
Bump bugfix for Issues (As 6.4.0 does not include the http_client fix):

* https://github.com/awslabs/logstash-output-amazon_es/issues/105
* https://github.com/awslabs/logstash-output-amazon_es/issues/101

### CODE REVIEW

**Comment by SharpEdgeMarshall** [comment]
Could you please merge this and release the fix?

**Comment by salman-ahmad** [comment]
@xyq164202 

Could you please merge this PR and release the fix?

**Comment by lifeofguenter** [comment]
🙏

**Comment by mikimichaeli** [comment]
@xyq164202 please merge this PR, this fix is very much needed.

**Comment by SharpEdgeMarshall** [comment]
This is a blocking issue, we can't use templates at the moment.

**Comment by musabqamri123** [comment]
this latest version 6.4.1 is not yet published on https://rubygems.org/gems/logstash-output-amazon_es

**Comment by SharpEdgeMarshall** [comment]
@xyq164202 Could you please release 6.4.1 on rubygems?

**Comment by malpani** [comment]
We released to rubygems yesterday. Apologies for the long wait here
https://rubygems.org/gems/logstash-output-amazon_es

**Pull request merged**
