### PR TITLE
add support for parent

### PR DESCRIPTION
**Pull request by sloba88**
Added missing support for parent field:
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-parent

### CODE REVIEW

**Comment by eecue** [comment]
Oh nice, so this worked out?  Can we get this merged in?

**Comment by eecue** [comment]
@msfroh can you merge this in?

**Comment by taru-m** [comment]
@sloba88 @eecue Hi, Please tell me the progress. I want to use parent-child.

**Comment by xyq164202** [comment]
Already support in the new code

**Comment by outis10** [comment]
Hi, I think that you need to reopen this issue that because I try to insert childs in my index and I get an error.
But when i review your code from master  I don't see any line about routing or parent as you merge in this ticket [https://github.com/awslabs/logstash-output-amazon_es/pull/68/commits/ce831bb0904b7f969ba97e7b4c1c3ad913d242fb](url).

This is the file amazon_es.rb
In  branch 6.0  the same file has this line
 ```bash
# A routing override to be applied to all processed events.
 # This can be dynamic using the `%{foo}` syntax.
 config :routing, :validate => :string
 ```
but then dissapear in the subsequent merges

so I was wondering if the merge was lost on the way or they weren't supporting child anymore.
Thanks in advance

**Pull request closed without merging**
