### PR TITLE
Move CredentialProviderChain instantiation during initialize

### LINKED ISSUE #117: 6.4.x causing continuous calls to AWS Metadata
## Description
Upgrading from from `logstash-output-amazon_es` `6.0.0` to `6.4.0` we started to experience 2 calls/second to the AWS Metadata service to obtain credentials from AWS instead of 2 calls every 10/15 minutes.

We tried to compile and use version `6.4.1` of `logstash-output-amazon_es` but the issue persisted and probably is not connected to bugs #105 and #101 

## Workaround
Going back to `6.0.0` obviously solve the issue.

## Info
logstash-output-amazon_es: `6.4.0`/`6.4.1`
Logstash version: `6.5.1/6.4.1`

### PR DESCRIPTION
**Pull request by SharpEdgeMarshall**
Closes #117 

Not a ruby expert here,
Digging inside the code trying to solve #117 I saw that a new `CredentialProviderChain` is created for each request.
This could be "fine" if you use ENV vars or credentials file but in our case, we are using STS and this is causing a big number of request to the metadata service.

So the solution is to move the `CredentialProviderChain` instantiation during the initialize of the `ManticoreAdapter` Class

### CODE REVIEW

**Comment by SharpEdgeMarshall** [comment]
No feedback?

**Comment by crisidev** [comment]
We will be working on this soon. The priority now it to release version 6.4.1. Sorry for the delay, we will go through this code soon.

Thanks a million for your contribution!

**Comment by crisidev** [comment]
This LGTM. ETA for get this fully released is beginning of next week.

**Comment by SharpEdgeMarshall** [comment]
@crisidev We are using a fork of the 6.4.1 with this PR for at least 4 months and I can confirm it works flawlessly.

**Comment by crisidev** [comment]
Ok, good to know!

We have our internal testing and release process which will help us to scope possible bugs and issues, but it is really nice to see you already have it running. 

Thanks for the help! I'll keep you posted.

**Comment by salamanderrex** [comment]
LGTM. I will merge the code and release as 6.4.2.

**Pull request merged**
